### ISSUE TITLE
Initial replace

### ISSUE THREAD

**Issue by signalwerk** [olavoparno/istanbul-badges-readme#1]
Wow! This tool is exactly what I needed. Thank you! There is one minor issue on the initial replace. Once I corrected it manually the parser updates it later correct.

Markdown

```md
# Test

![Lines]

Check [here](https://github.com/olavoparno/istanbul-badges-readme) a cool tool.
```

first run

```md
# Test

![Lines]
https://img.shields.io/badge/Coverage-100%25-brightgreen.svg) a cool tool.
```

expected

```md
# Test

![Lines](https://img.shields.io/badge/Coverage-100%25-brightgreen.svg)

Check [here](https://github.com/olavoparno/istanbul-badges-readme) a cool tool.
```

**Comment by olavoparno** [comment]
Hey, first of all, sorry for the delay!

Thanks for the issue. I will definitely look into it. Very much obliged for the detailed explanation!

**Comment by olavoparno** [comment]
Hello again, mister @signalwerk 

I have read my code all over and here are my considerations:

`![Branches](#branches#)`

I need to know where to begin and where to end so that I can update it with the badge URL and in order to do it I currently use the **parenthesis** (have to change it in the README, sorry!)

Please let me know if this would be a problem for you and if so, I am open to suggestions, please haha

Thank you again!

**Comment by olavoparno** [comment]
@all-contributors please add @signalwerk for question, doc

**Comment by olavoparno** [comment]
Hey, mister @signalwerk, is it ok for you to use the markup like this? `![Lines](#lines#)`

**Comment by olavoparno** [comment]
Sorry for the inconvenience. Closing issue.
