### ISSUE TITLE
feature request: add custom --style argument

### ISSUE THREAD

**Issue by liaoliaots** [olavoparno/istanbul-badges-readme#52]
**Is your feature request related to a problem? Please describe.**
A badge has a few style: flat, plastic, flat-square, etc. Maybe it's a good choice to specify via `--style` custom argument.

flat-square:
![](https://img.shields.io/badge/statements-100%25-brightgreen.svg?style=flat-square)

flat:
![](https://img.shields.io/badge/statements-100%25-brightgreen.svg?style=flat)

**Describe the solution you'd like**
via `--style` argument

**Describe alternatives you've considered**

**Additional context**

**Comment by olavoparno** [comment]
@liaoliaots thanks for opening the issue/suggestion! Yes, it would be nice to choose between styles since we use from shields.io. I once thought of even creating a markup on HTML to support extra styling alongside the markdown one but I never had the will to do it hahaha anyway, I think this is feasible and I will look into it ASAP, ok?

**Comment by liaoliaots** [comment]
Works fine. Thank you very much.

(⁎⁍̴̛ᴗ⁍̴̛⁎)(⁎⁍̴̛ᴗ⁍̴̛⁎)(⁎⁍̴̛ᴗ⁍̴̛⁎)
